previewsEnabled: true
previewsExpireAfterDays: 1

databases:
  - name: my_db
    plan: starter
    previewPlan: starter

services:
  - type: redis
    name: sidekiq_redis
    plan: starter
    ipAllowList: [ ]
  - type: redis
    name: cache_redis
    plan: starter
    ipAllowList: [ ]
  - type: web
    name: app
    env: ruby
    plan: starter
    previewPlan: starter
    branch: main
    buildCommand: "./bin/build"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq_redis
          property: connectionString
      - key: CACHE_REDIS_URL
        fromService:
          type: redis
          name: cache_redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: my_db
          property: connectionString
  - type: worker
    name: my_worker
    env: ruby
    plan: starter
    previewPlan: starter
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: CACHE_REDIS_URL
        fromService:
          type: redis
          name: cache_redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: my_db
          property: connectionString
